# Generated by Django 3.2.6 on 2021-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='shift',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
