# Generated by Django 3.2.6 on 2021-09-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_report_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='value2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='value3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
