# Generated by Django 3.2.6 on 2021-09-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_auto_20210915_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanok',
            name='norma_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
