# Generated by Django 3.2.6 on 2021-09-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_stanok_norma_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stanok',
            name='workers',
        ),
        migrations.AddField(
            model_name='stanok',
            name='workers',
            field=models.ManyToManyField(blank=True, to='statistic.Worker'),
        ),
    ]
